"""
hands/core/__init__.py

Importing this module registers all built-in hands
into the HandRegistry automatically.
"""

from francis_suite.hands.core import log
from francis_suite.hands.core import box_def
from francis_suite.hands.core import box
from francis_suite.hands.core import shared_box_def
from francis_suite.hands.core import shared_box
from francis_suite.hands.core import sleep
from francis_suite.hands.core import sleep_min
from francis_suite.hands.core import sleep_avg
from francis_suite.hands.core import sleep_max
from francis_suite.hands.core import httpx_call
from francis_suite.hands.core import httpx_cookie_jar
from francis_suite.hands.core import httpx_introspect
from francis_suite.hands.core import set_proxy
from francis_suite.hands.core import convert_html_to_xml
from francis_suite.hands.core import convert_binary_to_base64
from francis_suite.hands.core import convert_base64_to_binary
from francis_suite.hands.core import convert_text_to_base64
from francis_suite.hands.core import convert_base64_to_text
from francis_suite.hands.core import convert_json_to_csv
from francis_suite.hands.core import convert_csv_to_json
from francis_suite.hands.core import convert_xml_to_csv
from francis_suite.hands.core import convert_text_to_url
from francis_suite.hands.core import convert_url_to_text
from francis_suite.hands.core import convert_html_entities_to_text
from francis_suite.hands.core import convert_json_to_xml
from francis_suite.hands.core import convert_xml_to_json
from francis_suite.hands.core import xpath_extract
from francis_suite.hands.core import loop
from francis_suite.hands.core import loop_list
from francis_suite.hands.core import loop_body
from francis_suite.hands.core import case_
from francis_suite.hands.core import if_
from francis_suite.hands.core import else_
from francis_suite.hands.core import while_
from francis_suite.hands.core import try_
from francis_suite.hands.core import catch_
from francis_suite.hands.core import function_create
from francis_suite.hands.core import function_call
from francis_suite.hands.core import function_param
from francis_suite.hands.core import function_return
from francis_suite.hands.core import regex
from francis_suite.hands.core import regex_pattern
from francis_suite.hands.core import regex_input
from francis_suite.hands.core import regex_result
from francis_suite.hands.core import compose
from francis_suite.hands.core import text_split
from francis_suite.hands.core import evaluate
from francis_suite.hands.core import exit_
from francis_suite.hands.core import build_list
from francis_suite.hands.core import call_workflow
from francis_suite.hands.core import file_read
from francis_suite.hands.core import file_write
from francis_suite.hands.core import file_manage
from francis_suite.hands.core import pause_task
from francis_suite.hands.core import session_pulse
from francis_suite.hands.core import record_create
from francis_suite.hands.core import record_add
from francis_suite.hands.core import record_last_added
from francis_suite.hands.core import record_count
from francis_suite.hands.core import record_save
from francis_suite.hands.core import record_save_metadata
from francis_suite.hands.core import record_private_metadata