"""
francis_suite/schema_gen.py

Generate XML Schema (XSD) and a JSON manifest for registered workflow hands.
Importing all core hands populates HandRegistry; this module reads it and writes:

  - schema/francis-workflow.xsd — use with Red Hat XML / xml.fileAssociations
  - schema/francis-workflow.schema.json — tag registry + metadata for tooling
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from xml.sax.saxutils import escape


def _ensure_hands_loaded() -> None:
    # Side effect: registers all built-in hands
    import francis_suite.hands.core  # noqa: F401


def registered_tags_sorted() -> list[str]:
    _ensure_hands_loaded()
    from francis_suite.core.registry import HandRegistry

    return sorted(HandRegistry.instance().all_tags())


def build_xsd(tags: list[str]) -> str:
    """
    Build a minimal XSD: root <francis-workflow> with a choice of all hand elements.
    Each hand allows mixed content, arbitrary child elements, and arbitrary attributes
    (lax) so validation focuses on known tag names without duplicating every attribute.
    """
    ns_xs = "http://www.w3.org/2001/XMLSchema"
    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<xs:schema xmlns:xs="{ns_xs}" elementFormDefault="qualified" '
        'attributeFormDefault="unqualified">',
        '  <!-- Auto-generated by francis-suite schema. Do not edit by hand. -->',
        "",
        '  <xs:complexType name="HandMixedType" mixed="true">',
        "    <xs:sequence>",
        '      <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax"/>',
        "    </xs:sequence>",
        '    <xs:anyAttribute processContents="lax"/>',
        "  </xs:complexType>",
        "",
        '  <xs:element name="francis-workflow">',
        "    <xs:complexType>",
        "      <xs:sequence>",
        '        <xs:choice minOccurs="0" maxOccurs="unbounded">',
    ]
    for tag in tags:
        safe = escape(tag, {'"': "&quot;", "'": "&apos;"})
        lines.append(f'          <xs:element name="{safe}" type="HandMixedType"/>')
    lines.extend(
        [
            "        </xs:choice>",
            "      </xs:sequence>",
            '      <xs:anyAttribute processContents="lax"/>',
            "    </xs:complexType>",
            "  </xs:element>",
            "",
            "</xs:schema>",
            "",
        ]
    )
    return "\n".join(lines)


def build_json_manifest(tags: list[str], *, version: str) -> dict:
    """
    Machine-readable registry for tooling (tag list, version).
    For XML validation in the editor, use francis-workflow.xsd via xml.fileAssociations.
    """
    return {
        "_generator": "francis-suite schema",
        "francis_suite_version": version,
        "generated_for": "francis-workflow",
        "root_element": "francis-workflow",
        "xsd_file": "francis-workflow.xsd",
        "hand_tags": tags,
    }


def write_schemas(out_dir: Path, *, version: str) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    tags = registered_tags_sorted()
    xsd_path = out_dir / "francis-workflow.xsd"
    json_path = out_dir / "francis-workflow.schema.json"

    xsd_path.write_text(build_xsd(tags), encoding="utf-8")
    manifest = build_json_manifest(tags, version=version)
    json_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return xsd_path, json_path


def _default_version_string() -> str:
    try:
        from importlib.metadata import version as pkg_version

        return pkg_version("francis-suite")
    except Exception:
        return "0.1.0"


def main(argv: list[str] | None = None) -> int:
    import argparse

    p = argparse.ArgumentParser(
        prog="francis-suite schema",
        description="Write XSD and JSON manifest for registered workflow hands.",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=Path("schema"),
        help="Output directory (default: ./schema)",
    )
    p.add_argument(
        "--version",
        default=None,
        help="Version string embedded in the JSON manifest (default: package version)",
    )
    args = p.parse_args(argv)
    ver = args.version if args.version is not None else _default_version_string()

    xsd_path, json_path = write_schemas(args.out, version=ver)
    print(f"[OK] Wrote {xsd_path.as_posix()}")
    print(f"[OK] Wrote {json_path.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
